"""empty message

Revision ID: 5642e9c3fe1f
Revises: 90c1a24dce8b
Create Date: 2020-01-27 18:19:26.336202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5642e9c3fe1f'
down_revision = '90c1a24dce8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('score', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
