"""empty message

Revision ID: 90c1a24dce8b
Revises: 0005f748d4c7
Create Date: 2020-01-27 18:18:22.458289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c1a24dce8b'
down_revision = '0005f748d4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('score', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
