"""empty message

Revision ID: dfdac93d5dfe
Revises: 5642e9c3fe1f
Create Date: 2020-01-27 18:19:49.168192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdac93d5dfe'
down_revision = '5642e9c3fe1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('score', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
